interlay/interbtc-spec

- interbtc-spec/docs/source/spec/oracle.rst
> refactor: update oracle spec with pre and post conditions

- btcrelay-spec/docs/source/intro/bitcoin.rst
- btcrelay-spec/docs/source/spec/functions.rst
As per https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki#spv-clients .
Parachain PR [here](https://github.com/interlay/interbtc/pull/174)
> doc: specify minimum block version

- interbtc-spec/docs/source/spec/fee.rst
- interbtc-spec/docs/source/spec/issue.rst
- interbtc-spec/docs/source/spec/redeem.rst
- interbtc-spec/docs/source/spec/replace.rst
- interbtc-spec/docs/source/spec/vault-registry.rst
> refactor: update fee spec with pre and post conditions

- interbtc-spec/docs/source/spec/replace.rst
> refactor: update replace spec

- interbtc-spec/docs/source/spec/collateral.rst
> refactor: update collateral spec with pre and post conditions

- interbtc-spec/docs/source/spec/treasury.rst
> refactor: update treasury spec with pre and post conditions

- interbtc-spec/docs/source/spec/redeem.rst
- there is no longer a punishment fee that goes to the fee pool - it all goes to the user now
- renamed some vars
> fix: update redeem spec

- interbtc-spec/README.md
- interbtc-spec/docs/source/economics/fees.rst
- interbtc-spec/docs/source/economics/incentives.rst
- interbtc-spec/docs/source/intro/CbA.rst
- interbtc-spec/docs/source/intro/architecture.rst
- interbtc-spec/docs/source/intro/at-a-glance.rst
- interbtc-spec/docs/source/security_performance/liquidations.rst
- interbtc-spec/docs/source/security_performance/security-analysis.rst
- interbtc-spec/docs/source/spec/btc-relay.rst
- interbtc-spec/docs/source/spec/redeem.rst
- interbtc-spec/docs/source/spec/refund.rst
- interbtc-spec/docs/source/spec/relay.rst
- interbtc-spec/docs/source/spec/vault-registry.rst
> chore: interbtc -> interBTC

- interbtc-spec/docs/source/economics/SLA.rst
- interbtc-spec/docs/source/economics/fees.rst
- interbtc-spec/docs/source/economics/incentives.rst
- interbtc-spec/docs/source/intro/architecture.rst
- interbtc-spec/docs/source/security_performance/security-analysis.rst
- interbtc-spec/docs/source/spec/sla.rst
> chore: remove staked relayer roles

- interbtc-spec/docs/source/spec/issue.rst
> feat: add issue dust amount to spec

- interbtc-spec/docs/source/spec/fee.rst
- interbtc-spec/docs/source/spec/nomination.rst
- interbtc-spec/docs/source/spec/oracle.rst
- interbtc-spec/docs/source/spec/redeem.rst
- interbtc-spec/docs/source/spec/relay.rst
- interbtc-spec/docs/source/spec/sla.rst
- interbtc-spec/docs/source/spec/vault-registry.rst
> refactor: de-duplicate event definitions

- interbtc-spec/docs/source/spec/redeem.rst
> refactor: vault does not pay redeem fee if redeemer == vault

- interbtc-spec/docs/source/spec/issue.rst
- interbtc-spec/docs/source/spec/replace.rst
> chore: clarify that fee model is integrated

- interbtc-spec/docs/source/spec/fee.rst
- interbtc-spec/docs/source/spec/refund.rst
> feat: add request refund fn

- interbtc-spec/docs/source/spec/issue.rst
- interbtc-spec/docs/source/spec/reward.rst
- interbtc-spec/docs/source/spec/vault-registry.rst
> refactor: cleanup vault-registry spec and integrate staking / rewards

- interbtc-spec/docs/source/spec/introduction.rst
> chore: specify function visibility in intro

- interbtc-spec/docs/source/conf.py
- interbtc-spec/docs/source/spec/staking.rst
> refactor: remove unslashing

- interbtc-spec/docs/source/intro/architecture.rst
- interbtc-spec/docs/source/spec/oracle.rst
> chore: rename to oracle

- interbtc-spec/docs/source/spec/issue.rst
- interbtc-spec/docs/source/spec/redeem.rst
- interbtc-spec/docs/source/spec/replace.rst
This PR suggests a few very minor fixes/alterations surfaced from @informalsystems' audit of interlay/btc-parachain at
75fd3e2
The only suggestion that has any substance is that in 655f606, please see that commit for details.
> [IF-INTERLAY2-06], [IF-INTERLAY2-07] Minor suggestions on Issue, Redeem, and Replace specs

- interbtc-spec/docs/source/conf.py
- interbtc-spec/docs/source/spec/vault-registry.rst
> refactor: specify conditions that affect liquidationCollateral

- interbtc-spec/docs/source/spec/fee.rst
- interbtc-spec/docs/source/spec/vault-registry.rst
Closes https://github.com/interlay/interbtc-spec/issues/50
> feat: add theft fee upper bound

- interbtc-spec/docs/source/spec/nomination.rst
https://github.com/informalsystems/audit-interlay/pull/19
> audit: resolve IF-INTERLAY2-11 discrepancies

- interbtc-spec/docs/source/spec/fee.rst
https://github.com/informalsystems/audit-interlay/pull/17
> audit: resolve IF-INTERLAY2-09 discrepancies

- interbtc-spec/docs/source/spec/refund.rst
https://github.com/informalsystems/audit-interlay/pull/16
> audit: resolve IF-INTERLAY2-08 discrepancies

- interbtc-spec/docs/source/spec/replace.rst
https://github.com/informalsystems/audit-interlay/pull/18
> audit: resolve IF-INTERLAY2-10 discrepancies

- interbtc-spec/docs/source/spec/issue.rst
https://github.com/informalsystems/audit-interlay/pull/14
> audit: resolve IF-INTERLAY2-06 discrepancies

- interbtc-spec/docs/source/spec/redeem.rst
https://github.com/informalsystems/audit-interlay/pull/15
> audit: resolve IF-INTERLAY2-07 discrepancies

- docs/spec/oracle.rst
> refactor!: remove unused Bitcoin fee estimates

- docs/economics/fees.rst
> fix: typo, should be requested

- docs/economics/fees.rst
> chore: clarify vault reward distribution example

- docs/economics/fees.rst
> feat: include griefing fees in the fee model

- docs/spec/governance.rst
> fix: remove zero-width space for latex build

- docs/index.rst
- docs/spec/escrow.rst
> feat: add escrow module spec for stake-to-vote locking

- docs/spec/oracle.rst
- docs/spec/vault-registry.rst
> refactor: use snake case for oracle spec

- docs/spec/relay.rst
> refactor: use snake case for relay spec

- docs/spec/escrow.rst
- requirements.txt
> refactor: add more details to escrow spec
